spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: wren-auth
          uri: http://wren-auth:5173
          predicates:
            - Path=/oauth
        - id: wren-ai-service
          uri: http://wren-ai-service:5555
          predicates:
            - Path=/ai/**
        - id: wren-engine
          uri: http://wren-engine:8080
          predicates:
            - Path=/api/**
        - id: ibis-server
          uri: http://ibis-server:8000
          predicates:
            - Path=/ibis/**
        - id: wren-ui-subpaths
          uri: http://wren-ui:3000
          predicates:
            - Path=/**
      
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
info:
  app:
    name: gateway-api
    description: Gateway API for Wren